### PR TITLE
Create PullUpBar

### PR DESCRIPTION
**Pull request by Legionof7**
One of the coolest programs ever created in the history of mankind. Other than LoL.

### CODE REVIEW

**Comment by Legionof7** [comment]
OMG IS THIS THE GREAT PETER SKIDMORE OUR LORD?

**Comment by ifd3f** [comment]
piiitah

**Comment by ptskidmore** [comment]
Just closing it so it stops harassing me.

**Comment by Legionof7** [comment]
Noooo Peter...

**Comment by codeWorth** [comment]
Well thanks my hopes and dreams are crushed. :/

**Pull request closed without merging**
